/* pdr_utils.h - simple helpers for accessing builder-generated PDR data
 *
 * Provides a minimal, project-local API used by the PLDM handlers to
 * access records in the __pdr_data[] blob generated by the iot_builder.
 */
#ifndef PDR_UTILS_H
#define PDR_UTILS_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Return the total number of bytes in the PDR repository as laid out in
 * the generated __pdr_data[] array (payload + per-record 10-byte headers).
 * If the builder-generated macros are available this derives the size from
 * PDR_TOTAL_SIZE and PDR_NUMBER_OF_RECORDS. Returns 0 if the size cannot be
 * determined.
 */
size_t pdr_repo_bytes(void);

/* Read the PDR record header at the given byte offset within the repository.
 * On success returns true and optionally populates *handle and *record_size
 * (record_size includes the 10-byte header + payload length). Returns false
 * if the offset is out-of-range or the record would overflow the repository.
 */
bool pdr_read_record_at(size_t offset, uint32_t *handle, size_t *record_size);

#ifdef __cplusplus
}
#endif

#endif /* PDR_UTILS_H */
/* PDR utility helpers
 * Provides helpers to compute repository byte length and parse records
 */
#ifndef PDR_UTILS_H
#define PDR_UTILS_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* Size of the PDR record header emitted by the builder */
#define PDR_HEADER_SIZE 10u

/* Return the total number of bytes present in __pdr_data[] on device
 * (payload bytes + per-record headers). */
size_t pdr_repo_bytes(void);

/* Read a record at `offset` within the repo. On success returns true and
 * writes the record handle and total record size (header+payload) into
 * `handle` and `record_size` respectively. */
bool pdr_read_record_at(size_t offset, uint32_t *handle, size_t *record_size);

#endif /* PDR_UTILS_H */
